#!/usr/bin/env python
""" 
Adds a collision object representing the table to the planning scene
Loads a list of waypoints from the parameter server (if waypoints don't exist, the list is empty)

PUBLISHERS:
  + /move_group/display_planned_path moveit_msgs.msg.DisplayTrajectory ~ the velocity of the turtlesim

SERVICES:
  + /px100/reset reset ~ Spawns an obstacle collision object in Rviz at a specified location; optionally clears waypoints on parameter server 
  + /px100/step step ~ Moves robot arm to specified position and gripper state; adds successful positions to waypoints parameter; returns MoveItErroCode
  + /px100/follow follow ~ Moves arm through iteration of waypoints specified in .yaml file; can perform once or loop
"""

import sys
import rospy
from std_srvs.srv import EmptyResponse
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg
from arm_move.srv import reset, step, follow, resetResponse
from moveit_commander.conversions import pose_to_list

class Mover:
    def __init__(self):
        """ Initialization for Mover class."""
        # Initialize MoveIt Commander
        moveit_commander.roscpp_initialize(sys.argv)

        # Initialize node
        rospy.init_node('mover')

        # Initialize MoveIt Commander things
        self.scene = moveit_commander.PlanningSceneInterface()
        self.move_gripper = moveit_commander.MoveGroupCommander("interbotix_gripper")
        self.group_name = "interbotix_arm"
        self.move_group = moveit_commander.MoveGroupCommander(self.group_name)

        # Variables
        self.box_name = ""
        self.waypoints = []

        # Create services
        self.reset = rospy.Service("reset", reset, self.reset_func) # Create reset service
        self.step = rospy.Service("step", step, self.step_func) # Create step service
        self.follow = rospy.Service("follow", follow, self.follow_func) # Create follow service

        # Add table collision object to Rviz
        self.add_table()


    def wait_for_state_update(self, box_is_known=False, box_is_attached=False, timeout=4):
        """
        This function was included with the MoveIt collision object creation example.
        """
        box_name = self.box_name
        scene = self.scene

        start = rospy.get_time()
        seconds = rospy.get_time()
        while (seconds - start < timeout) and not rospy.is_shutdown():
            # Test if the box is in attached objects
            attached_objects = scene.get_attached_objects([box_name])
            is_attached = len(attached_objects.keys()) > 0

            # Test if the box is in the scene.
            # Note that attaching the box will remove it from known_objects
            is_known = box_name in scene.get_known_object_names()

            # Test if we are in the expected state
            if (box_is_attached == is_attached) and (box_is_known == is_known):
                return True

            # Sleep so that we give other threads time on the processor
            rospy.sleep(0.1)
            seconds = rospy.get_time()

        # If we exited the while loop without returning then we timed out
        return False

    def reset_func(self, data):
        """
        Spawns collision box object into Rviz; moves robot to 'Home' position;
        clears waypoint param if desired.

        Args:
           self : Mover class
           data : arguments given via service call (box position and waypoint clearing status)

        Returns:
           resetResponse
        """
        x = data.box_pose.x
        y = data.box_pose.y
        clear_wp = data.clear_wp

        self.add_obstacle(x, y)
        self.move_group.set_named_target("Home")
        self.move_group.go()

        if clear_wp == True:
            self.waypoints = []
        else:
            pass
        
        return resetResponse() 

    def step_func(self, data):
        """
        Moves robot to inputted position and gripper state.

        Args:
           self : Mover class
           data : arguments given via service call (end-effector position and gripper state)
           Gripper closes if true, opens if false.

        Returns:
           err.val : MoveItErrorCode (1 for successful motion plan, -1 for failed motion plan)
        """
        # Retrieve position data from argument
        x = data.coordinates.x
        y = data.coordinates.y
        z = data.coordinates.z
        xyz = [x,y,z]

        # Set position target, plan path, and move robot
        self.move_group.set_position_target(xyz)
        success, traj_msg, planTime, err = self.move_group.plan()
        self.move_group.execute(traj_msg, wait='true')
        self.move_group.stop()

        # If True, close gripper, if False, open gripper
        if data.gripper == True:
            self.move_gripper.set_named_target('Closed')
        elif data.gripper == False:
            self.move_gripper.set_named_target('Open')
        
        # Move gripper
        self.move_gripper.go(wait='true')
        self.move_gripper.stop()

        # Save waypoints to parameter server if legal
        if err.val == 1:
            current_robot_pose = [xyz[0], xyz[1], xyz[2], data.gripper]
            self.waypoints.append(current_robot_pose)
        else:
            rospy.logerr("Sorry, that pose is too extreme for me! I haven't been practicing my yoga. Try another pose.")

        return err.val

    def follow_func(self, data):
        """
        Moves robot iteratively through waypoints specified in .yaml file.

        Args:
           self : Mover class
           data : arguments given via service call (boolean determining if pattern should loop)

        Returns:
           Empty list []
        """
        custom = data.custom
        if custom == True:
            follow_waypoints = self.waypoints
        elif custom == False:
            # Retrieve waypoints from .yaml file
            follow_waypoints = rospy.get_param('/waypoints')

        # Retrieve loop status
        repeat = data.repeat
        
        # If loop desired, continue to loop
        if repeat == True:
            while True:
                for wp in follow_waypoints:
                    xyz = [wp[0], wp[1], wp[2]]
                    grip = wp[3]
                    self.move_group.set_position_target(xyz)
                    success, traj_msg, planTime, err = self.move_group.plan()
                    self.move_group.execute(traj_msg, wait='true')
                    self.move_group.stop()

                    if grip == True:
                        self.move_gripper.set_named_target('Closed')
                    elif grip == False:
                        self.move_gripper.set_named_target('Open')
                    
                    self.move_gripper.go(wait='true')
                    self.move_gripper.stop()

        # If loop not desired, perform once
        elif repeat == False:
            for wp in follow_waypoints:
                xyz = [wp[0], wp[1], wp[2]]
                grip = wp[3]
                self.move_group.set_position_target(xyz)
                success, traj_msg, planTime, err = self.move_group.plan()
                self.move_group.execute(traj_msg, wait='true')

                self.move_group.stop()

                if grip == True:
                    self.move_gripper.set_named_target('Closed')
                elif grip == False:
                    self.move_gripper.set_named_target('Open')
                
                self.move_gripper.go(wait='true')
                self.move_gripper.stop()
        
        return []

    def add_table(self, timeout=5):
        """
        Adds table collision object to Rviz.

        Args:
           self : Mover class
           timeout : sets timeout for table

        Returns:
           self.wait_for_state_update(box_is_known=True, timeout=timeout)
        """
        # Sleep to allow Rviz to load before adding object
        rospy.sleep(2)

        # Initialize table object
        scene = self.scene
        box_pose = geometry_msgs.msg.PoseStamped()
        box_pose.header.frame_id = "world"
        box_pose.pose.orientation.w = 1.0
        box_pose.pose.position.x = 0
        box_pose.pose.position.y = 0
        box_pose.pose.position.z = -0.025
        self.box_name = "table"

        # Add table object to Rviz
        scene.add_box(self.box_name, box_pose, size=(1,1,0.05))

        return self.wait_for_state_update(box_is_known=True, timeout=timeout)

    def add_obstacle(self, x, y, timeout=4):
        """
        Adds collision object to Rviz.

        Args:
           self : Mover class
           x: x position of collision object on table
           y: y position of collision object on table
           timeout : sets timeout for table

        Returns:
           self.wait_for_state_update(box_is_known=True, timeout=timeout)
        """

        # Initialize obstacle object
        scene = self.scene
        obst_pose = geometry_msgs.msg.PoseStamped()
        obst_pose.header.frame_id = "world"
        obst_pose.pose.orientation.w = 1.0
        obst_pose.pose.position.x = x
        obst_pose.pose.position.y = y
        obst_pose.pose.position.z = 0.07
        self.obst_name = "realsense"

        # Add obstacle object to Rviz
        scene.add_box(self.obst_name, obst_pose, size=(0.05,0.09,0.14))

        return self.wait_for_state_update(box_is_known=True, timeout=timeout)

if __name__ == '__main__':
    # Instantiate class
    Mover()

    # Spin() simply keeps python from exiting until this node is stopped
    rospy.spin()